services:
  db:
    image: postgres:13.1-alpine
    container_name: db
    hostname: db
    environment:
      POSTGRES_DB: demo_trial
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5431:5432"
    volumes:
      - my-volume:/container/path

  server:
    image: docker-spring-boot-postgres:latest
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/demo_trial
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO : update
    depends_on:
      - db
    ports:
      - "8081:8080"

volumes:
  my-volume:


